export const categoryCriteria = {
  'sales-outreach': [
    { key: 'starting_price_usd', label: 'Starting price', type: 'price' },
    { key: 'has_free_plan', label: 'Free plan', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Works in Brazil', type: 'boolean' },
    { key: 'accepts_brl', label: 'Accepts BRL', type: 'boolean' },
    { key: 'has_pt_support', label: 'PT support', type: 'boolean' },
    { key: 'has_latam_data', label: 'LATAM data', type: 'boolean' },
    { key: 'pricing_model', label: 'Billing', type: 'text' },
  ],
  'sdr-automation': [
    { key: 'starting_price_usd', label: 'Starting price', type: 'price' },
    { key: 'has_free_plan', label: 'Free plan', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Works in Brazil', type: 'boolean' },
    { key: 'accepts_brl', label: 'Accepts BRL', type: 'boolean' },
    { key: 'has_pt_support', label: 'PT support', type: 'boolean' },
    { key: 'has_latam_data', label: 'LATAM data', type: 'boolean' },
    { key: 'pricing_model', label: 'Billing', type: 'text' },
  ],
  'crm-automation': [
    { key: 'starting_price_usd', label: 'Starting price', type: 'price' },
    { key: 'has_free_plan', label: 'Free plan', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Works in Brazil', type: 'boolean' },
    { key: 'accepts_brl', label: 'Accepts BRL', type: 'boolean' },
    { key: 'has_pt_support', label: 'PT support', type: 'boolean' },
    { key: 'has_es_support', label: 'ES support', type: 'boolean' },
    { key: 'has_latam_data', label: 'LATAM data', type: 'boolean' },
    { key: 'pricing_model', label: 'Billing', type: 'text' },
  ],
  'customer-support': [
    { key: 'starting_price_usd', label: 'Starting price', type: 'price' },
    { key: 'has_free_plan', label: 'Free plan', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Works in Brazil', type: 'boolean' },
    { key: 'accepts_brl', label: 'Accepts BRL', type: 'boolean' },
    { key: 'has_pt_support', label: 'PT support', type: 'boolean' },
    { key: 'has_es_support', label: 'ES support', type: 'boolean' },
    { key: 'pricing_model', label: 'Billing', type: 'text' },
  ],
  'customer-success': [
    { key: 'starting_price_usd', label: 'Starting price', type: 'price' },
    { key: 'has_free_plan', label: 'Free plan', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Works in Brazil', type: 'boolean' },
    { key: 'accepts_brl', label: 'Accepts BRL', type: 'boolean' },
    { key: 'has_pt_support', label: 'PT support', type: 'boolean' },
    { key: 'has_latam_data', label: 'LATAM data', type: 'boolean' },
    { key: 'pricing_model', label: 'Billing', type: 'text' },
  ],
  'marketing-automation': [
    { key: 'starting_price_usd', label: 'Starting price', type: 'price' },
    { key: 'has_free_plan', label: 'Free plan', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Works in Brazil', type: 'boolean' },
    { key: 'accepts_brl', label: 'Accepts BRL', type: 'boolean' },
    { key: 'has_pt_support', label: 'PT support', type: 'boolean' },
    { key: 'has_latam_data', label: 'LATAM data', type: 'boolean' },
    { key: 'pricing_model', label: 'Billing', type: 'text' },
  ],
  'revenue-operations': [
    { key: 'starting_price_usd', label: 'Starting price', type: 'price' },
    { key: 'has_free_plan', label: 'Free plan', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Works in Brazil', type: 'boolean' },
    { key: 'has_pt_support', label: 'PT support', type: 'boolean' },
    { key: 'has_latam_data', label: 'LATAM data', type: 'boolean' },
    { key: 'pricing_model', label: 'Billing', type: 'text' },
  ],
  'hr-automation': [
    { key: 'starting_price_usd', label: 'Starting price', type: 'price' },
    { key: 'has_free_plan', label: 'Free plan', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Works in Brazil', type: 'boolean' },
    { key: 'accepts_brl', label: 'Accepts BRL', type: 'boolean' },
    { key: 'has_pt_support', label: 'PT support', type: 'boolean' },
    { key: 'has_latam_data', label: 'LATAM data', type: 'boolean' },
    { key: 'pricing_model', label: 'Billing', type: 'text' },
  ],
};

export const curatedComparisons = [
  { category: 'sales-outreach', slugA: 'clay', slugB: 'apollo-io' },
  { category: 'sales-outreach', slugA: 'instantly', slugB: 'smartlead' },
  { category: 'sales-outreach', slugA: 'lemlist', slugB: 'reply-io' },
  { category: 'sales-outreach', slugA: 'salesloft', slugB: 'outreach' },
  { category: 'sdr-automation', slugA: 'clay', slugB: 'apollo-io' },
  { category: 'sdr-automation', slugA: 'instantly', slugB: 'smartlead' },
  { category: 'sdr-automation', slugA: 'salesloft', slugB: 'outreach' },
  { category: 'crm-automation', slugA: 'hubspot-sales', slugB: 'pipedrive' },
  { category: 'customer-support', slugA: 'zendesk', slugB: 'freshdesk' },
  { category: 'customer-support', slugA: 'zendesk', slugB: 'intercom' },
  { category: 'customer-support', slugA: 'intercom', slugB: 'freshdesk' },
  { category: 'customer-success', slugA: 'intercom', slugB: 'zendesk' },
  { category: 'customer-success', slugA: 'hubspot-sales', slugB: 'freshdesk' },
  { category: 'marketing-automation', slugA: 'hubspot-sales', slugB: 'activecampaign' },
  { category: 'marketing-automation', slugA: 'activecampaign', slugB: 'mailchimp' },
  { category: 'marketing-automation', slugA: 'rd-station', slugB: 'activecampaign' },
  { category: 'revenue-operations', slugA: 'gong', slugB: 'chorus' },
  { category: 'hr-automation', slugA: 'gupy', slugB: 'factorial-hr' },
  { category: 'hr-automation', slugA: 'rippling', slugB: 'workday' },
];
