export const categoryCriteria = {
  'sales-outreach': [
    { key: 'starting_price_usd', label: 'Starting price', type: 'price' },
    { key: 'has_free_plan', label: 'Free plan', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Works in Brazil', type: 'boolean' },
    { key: 'accepts_brl', label: 'Accepts BRL', type: 'boolean' },
    { key: 'has_pt_support', label: 'PT support', type: 'boolean' },
    { key: 'has_latam_data', label: 'LATAM data', type: 'boolean' },
    { key: 'pricing_model', label: 'Billing', type: 'text' },
  ],
  'sdr-automation': [
    { key: 'starting_price_usd', label: 'Starting price', type: 'price' },
    { key: 'has_free_plan', label: 'Free plan', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Works in Brazil', type: 'boolean' },
    { key: 'accepts_brl', label: 'Accepts BRL', type: 'boolean' },
    { key: 'has_pt_support', label: 'PT support', type: 'boolean' },
    { key: 'has_latam_data', label: 'LATAM data', type: 'boolean' },
    { key: 'pricing_model', label: 'Billing', type: 'text' },
  ],
  'crm-automation': [
    { key: 'starting_price_usd', label: 'Starting price', type: 'price' },
    { key: 'has_free_plan', label: 'Free plan', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Works in Brazil', type: 'boolean' },
    { key: 'accepts_brl', label: 'Accepts BRL', type: 'boolean' },
    { key: 'has_pt_support', label: 'PT support', type: 'boolean' },
    { key: 'has_es_support', label: 'ES support', type: 'boolean' },
    { key: 'has_latam_data', label: 'LATAM data', type: 'boolean' },
    { key: 'pricing_model', label: 'Billing', type: 'text' },
  ],
  'customer-support': [
    { key: 'starting_price_usd', label: 'Starting price', type: 'price' },
    { key: 'has_free_plan', label: 'Free plan', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Works in Brazil', type: 'boolean' },
    { key: 'accepts_brl', label: 'Accepts BRL', type: 'boolean' },
    { key: 'has_pt_support', label: 'PT support', type: 'boolean' },
    { key: 'has_es_support', label: 'ES support', type: 'boolean' },
    { key: 'pricing_model', label: 'Billing', type: 'text' },
  ],
  'customer-success': [
    { key: 'starting_price_usd', label: 'Starting price', type: 'price' },
    { key: 'has_free_plan', label: 'Free plan', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Works in Brazil', type: 'boolean' },
    { key: 'accepts_brl', label: 'Accepts BRL', type: 'boolean' },
    { key: 'has_pt_support', label: 'PT support', type: 'boolean' },
    { key: 'has_latam_data', label: 'LATAM data', type: 'boolean' },
    { key: 'pricing_model', label: 'Billing', type: 'text' },
  ],
  'marketing-automation': [
    { key: 'starting_price_usd', label: 'Starting price', type: 'price' },
    { key: 'has_free_plan', label: 'Free plan', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Works in Brazil', type: 'boolean' },
    { key: 'accepts_brl', label: 'Accepts BRL', type: 'boolean' },
    { key: 'has_pt_support', label: 'PT support', type: 'boolean' },
    { key: 'has_latam_data', label: 'LATAM data', type: 'boolean' },
    { key: 'pricing_model', label: 'Billing', type: 'text' },
  ],
  'revenue-operations': [
    { key: 'starting_price_usd', label: 'Starting price', type: 'price' },
    { key: 'has_free_plan', label: 'Free plan', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Works in Brazil', type: 'boolean' },
    { key: 'has_pt_support', label: 'PT support', type: 'boolean' },
    { key: 'has_latam_data', label: 'LATAM data', type: 'boolean' },
    { key: 'pricing_model', label: 'Billing', type: 'text' },
  ],
  'hr-automation': [
    { key: 'starting_price_usd', label: 'Starting price', type: 'price' },
    { key: 'has_free_plan', label: 'Free plan', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Works in Brazil', type: 'boolean' },
    { key: 'accepts_brl', label: 'Accepts BRL', type: 'boolean' },
    { key: 'has_pt_support', label: 'PT support', type: 'boolean' },
    { key: 'has_latam_data', label: 'LATAM data', type: 'boolean' },
    { key: 'pricing_model', label: 'Billing', type: 'text' },
  ],
  'voz-e-texto': [
    { key: 'starting_price_usd', label: 'Preço inicial', type: 'price' },
    { key: 'has_free_plan', label: 'Plano gratuito', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Funciona no Brasil', type: 'boolean' },
    { key: 'has_pt_support', label: 'Suporte em PT', type: 'boolean' },
    { key: 'pricing_model', label: 'Cobrança', type: 'text' },
  ],
  'assistentes-de-ia': [
    { key: 'starting_price_usd', label: 'Preço inicial', type: 'price' },
    { key: 'has_free_plan', label: 'Plano gratuito', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Funciona no Brasil', type: 'boolean' },
    { key: 'has_pt_support', label: 'Suporte em PT', type: 'boolean' },
    { key: 'pricing_model', label: 'Cobrança', type: 'text' },
  ],
  'ia-generativa': [
    { key: 'starting_price_usd', label: 'Preço inicial', type: 'price' },
    { key: 'has_free_plan', label: 'Plano gratuito', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Funciona no Brasil', type: 'boolean' },
    { key: 'has_pt_support', label: 'Suporte em PT', type: 'boolean' },
    { key: 'pricing_model', label: 'Cobrança', type: 'text' },
  ],
  'vendas-com-ia': [
    { key: 'starting_price_usd', label: 'Preço inicial', type: 'price' },
    { key: 'has_free_plan', label: 'Plano gratuito', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Funciona no Brasil', type: 'boolean' },
    { key: 'accepts_brl', label: 'Aceita BRL', type: 'boolean' },
    { key: 'has_pt_support', label: 'Suporte em PT', type: 'boolean' },
    { key: 'has_latam_data', label: 'Dados LATAM', type: 'boolean' },
    { key: 'pricing_model', label: 'Cobrança', type: 'text' },
  ],
  'suporte-com-ia': [
    { key: 'starting_price_usd', label: 'Preço inicial', type: 'price' },
    { key: 'has_free_plan', label: 'Plano gratuito', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Funciona no Brasil', type: 'boolean' },
    { key: 'has_pt_support', label: 'Suporte em PT', type: 'boolean' },
    { key: 'pricing_model', label: 'Cobrança', type: 'text' },
  ],
  'marketing-com-ia': [
    { key: 'starting_price_usd', label: 'Preço inicial', type: 'price' },
    { key: 'has_free_plan', label: 'Plano gratuito', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Funciona no Brasil', type: 'boolean' },
    { key: 'accepts_brl', label: 'Aceita BRL', type: 'boolean' },
    { key: 'has_pt_support', label: 'Suporte em PT', type: 'boolean' },
    { key: 'pricing_model', label: 'Cobrança', type: 'text' },
  ],
  'criacao-de-conteudo': [
    { key: 'starting_price_usd', label: 'Preço inicial', type: 'price' },
    { key: 'has_free_plan', label: 'Plano gratuito', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Funciona no Brasil', type: 'boolean' },
    { key: 'has_pt_support', label: 'Suporte em PT', type: 'boolean' },
    { key: 'pricing_model', label: 'Cobrança', type: 'text' },
  ],
  'criacao-de-video': [
    { key: 'starting_price_usd', label: 'Preço inicial', type: 'price' },
    { key: 'has_free_plan', label: 'Plano gratuito', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Funciona no Brasil', type: 'boolean' },
    { key: 'has_pt_support', label: 'Suporte em PT', type: 'boolean' },
    { key: 'pricing_model', label: 'Cobrança', type: 'text' },
  ],
  'texto-para-video': [
    { key: 'starting_price_usd', label: 'Preço inicial', type: 'price' },
    { key: 'has_free_plan', label: 'Plano gratuito', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Funciona no Brasil', type: 'boolean' },
    { key: 'has_pt_support', label: 'Suporte em PT', type: 'boolean' },
    { key: 'pricing_model', label: 'Cobrança', type: 'text' },
  ],
  'texto-para-imagem': [
    { key: 'starting_price_usd', label: 'Preço inicial', type: 'price' },
    { key: 'has_free_plan', label: 'Plano gratuito', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Funciona no Brasil', type: 'boolean' },
    { key: 'pricing_model', label: 'Cobrança', type: 'text' },
  ],
  'design-com-ia': [
    { key: 'starting_price_usd', label: 'Preço inicial', type: 'price' },
    { key: 'has_free_plan', label: 'Plano gratuito', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Funciona no Brasil', type: 'boolean' },
    { key: 'has_pt_support', label: 'Suporte em PT', type: 'boolean' },
    { key: 'pricing_model', label: 'Cobrança', type: 'text' },
  ],
  'produtividade-com-ia': [
    { key: 'starting_price_usd', label: 'Preço inicial', type: 'price' },
    { key: 'has_free_plan', label: 'Plano gratuito', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Funciona no Brasil', type: 'boolean' },
    { key: 'has_pt_support', label: 'Suporte em PT', type: 'boolean' },
    { key: 'pricing_model', label: 'Cobrança', type: 'text' },
  ],
  'reunioes-com-ia': [
    { key: 'starting_price_usd', label: 'Preço inicial', type: 'price' },
    { key: 'has_free_plan', label: 'Plano gratuito', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Funciona no Brasil', type: 'boolean' },
    { key: 'has_pt_support', label: 'Suporte em PT', type: 'boolean' },
    { key: 'pricing_model', label: 'Cobrança', type: 'text' },
  ],
  'codigo-com-ia': [
    { key: 'starting_price_usd', label: 'Preço inicial', type: 'price' },
    { key: 'has_free_plan', label: 'Plano gratuito', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Funciona no Brasil', type: 'boolean' },
    { key: 'pricing_model', label: 'Cobrança', type: 'text' },
  ],
  'seo-e-blog': [
    { key: 'starting_price_usd', label: 'Preço inicial', type: 'price' },
    { key: 'has_free_plan', label: 'Plano gratuito', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Funciona no Brasil', type: 'boolean' },
    { key: 'has_pt_support', label: 'Suporte em PT', type: 'boolean' },
    { key: 'pricing_model', label: 'Cobrança', type: 'text' },
  ],
  'criador-de-sites': [
    { key: 'starting_price_usd', label: 'Preço inicial', type: 'price' },
    { key: 'has_free_plan', label: 'Plano gratuito', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Funciona no Brasil', type: 'boolean' },
    { key: 'has_pt_support', label: 'Suporte em PT', type: 'boolean' },
    { key: 'pricing_model', label: 'Cobrança', type: 'text' },
  ],
  'chat-para-sites': [
    { key: 'starting_price_usd', label: 'Preço inicial', type: 'price' },
    { key: 'has_free_plan', label: 'Plano gratuito', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Funciona no Brasil', type: 'boolean' },
    { key: 'has_pt_support', label: 'Suporte em PT', type: 'boolean' },
    { key: 'pricing_model', label: 'Cobrança', type: 'text' },
  ],
  'fluxos-de-trabalho': [
    { key: 'starting_price_usd', label: 'Preço inicial', type: 'price' },
    { key: 'has_free_plan', label: 'Plano gratuito', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Funciona no Brasil', type: 'boolean' },
    { key: 'has_pt_support', label: 'Suporte em PT', type: 'boolean' },
    { key: 'pricing_model', label: 'Cobrança', type: 'text' },
  ],
  'operacoes-com-ia': [
    { key: 'starting_price_usd', label: 'Preço inicial', type: 'price' },
    { key: 'has_free_plan', label: 'Plano gratuito', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Funciona no Brasil', type: 'boolean' },
    { key: 'has_pt_support', label: 'Suporte em PT', type: 'boolean' },
    { key: 'pricing_model', label: 'Cobrança', type: 'text' },
  ],
  'suite-criativa': [
    { key: 'starting_price_usd', label: 'Preço inicial', type: 'price' },
    { key: 'has_free_plan', label: 'Plano gratuito', type: 'boolean' },
    { key: 'works_in_brazil', label: 'Funciona no Brasil', type: 'boolean' },
    { key: 'has_pt_support', label: 'Suporte em PT', type: 'boolean' },
    { key: 'pricing_model', label: 'Cobrança', type: 'text' },
  ],
};

export const curatedComparisons = [
  { category: 'sales-outreach', slugA: 'clay', slugB: 'apollo-io' },
  { category: 'sales-outreach', slugA: 'instantly', slugB: 'smartlead' },
  { category: 'sales-outreach', slugA: 'lemlist', slugB: 'reply-io' },
  { category: 'sales-outreach', slugA: 'salesloft', slugB: 'outreach' },
  { category: 'sdr-automation', slugA: 'clay', slugB: 'apollo-io' },
  { category: 'sdr-automation', slugA: 'instantly', slugB: 'smartlead' },
  { category: 'sdr-automation', slugA: 'salesloft', slugB: 'outreach' },
  { category: 'crm-automation', slugA: 'hubspot-sales', slugB: 'pipedrive' },
  { category: 'customer-support', slugA: 'zendesk', slugB: 'freshdesk' },
  { category: 'customer-support', slugA: 'zendesk', slugB: 'intercom' },
  { category: 'customer-support', slugA: 'intercom', slugB: 'freshdesk' },
  { category: 'customer-success', slugA: 'intercom', slugB: 'zendesk' },
  { category: 'customer-success', slugA: 'hubspot-sales', slugB: 'freshdesk' },
  { category: 'marketing-automation', slugA: 'hubspot-sales', slugB: 'activecampaign' },
  { category: 'marketing-automation', slugA: 'activecampaign', slugB: 'mailchimp' },
  { category: 'marketing-automation', slugA: 'rd-station', slugB: 'activecampaign' },
  { category: 'revenue-operations', slugA: 'gong', slugB: 'chorus' },
  { category: 'hr-automation', slugA: 'gupy', slugB: 'factorial-hr' },
  { category: 'hr-automation', slugA: 'rippling', slugB: 'workday' },
];
